[project]
name = 'DecentralizedFinance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lending-and-borrowing]
path = 'contracts/lending-and-borrowing.clar'
clarity_version = 2
epoch = 2.5

[contracts.yield-farming]
path = 'contracts/yield-farming.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
